#!/bin/sh
REPO_ROOT=$(git rev-parse --show-toplevel)
mkdir -p $REPO_ROOT/docs/new
cp $REPO_ROOT/docs/index.css $REPO_ROOT/docs/favicon.ico $REPO_ROOT/docs/new/
python3 $REPO_ROOT/generators/generate_sites.py
