name: gh pages deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate statics
        uses: purajit/YASS@v2.1
        with:
          yass-config-path: yass_config_prod.json

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/'

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
